### ISSUE TITLE
No Entities in Home Assistant

### ISSUE THREAD

**Issue by dajomas** [antonijn/mqtt4dsmr#3]
Python: 3.12.2
HA Core: 2024.2.0 (on a VM)
SmartMeter: Landis&Gyr E350 (DSMR 2.2+) 
P1 connected to an RPi via serial splitter (used ser2net in the past which worked but ser2net was not stable enough)

I created the following compose.yaml file:
```yaml
version: "3"

services:
  mqtt4dsmr:
    image: "ghcr.io/antonijn/mqtt4dsmr:latest"
    environment:
      MQTT_HOST: "***"
      MQTT_PORT: "1883"
      MQTT_USERNAME: "***"
      MQTT_PASSWORD: "***"
      DSMR_VERSION: V2_2
      SERIAL_SETTINGS: V2_2
    devices:
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0:/dev/ttyDSMR"
    restart: always

```
via MQTT Explorer, I can see a topic ```dsmr``` which only contains a ```status``` with value ```online``` but I can't find any entries in the homeassistant topic and in HA, I can't find any dsmr entries either.

Did I miss anything? Where should I find the dsmr entries in HA?

Thanx for your help.
